### ISSUE TITLE
访问报错

### ISSUE THREAD

**Issue by azishabibi** [WhymustIhaveaname/TsinghuaTunet#12]

**Comment by azishabibi** [comment]
auth4: python test.py --connect-auth4
23/05/14 23:21:26 783 [WARNING,auth_login:146] get ac_id return 'fail', set it to 1
23/05/14 23:21:26 783 [INFO,auth_login:147] comment: ac_id 与网段（地理位置有关），本报错发生概率不高。如果您看到这条消息并且不能联网，请去 https://github.com/WhymustIhaveaname/TsinghuaTunet/issues 提交 issue，我会在一天内回复。
23/05/14 23:21:26 817 [INFO,auth_login:174] {'client_ip': '166.111.81.34', 'error': 'ok', 'res': 'ok', 'suc_msg': 'ip_already_online_error'}


auth6: python test.py --connect-auth6
23/05/14 23:23:47 226 [ERROR,auth_login:134] get challenge failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f46c1d69240>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='auth6.tsinghua.edu.cn', port=443): Max retries exceeded with url: /cgi-bin/get_challenge?callback=callback&username=liuzheqi20&ip=&double_stack=1&_=1684077827222 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46c1d69240>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 126, in auth_login
    g1=requests.get(url,headers=headers,params=params,timeout=TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='auth6.tsinghua.edu.cn', port=443): Max retries exceeded with url: /cgi-bin/get_challenge?callback=callback&username=liuzheqi20&ip=&double_stack=1&_=1684077827222 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46c1d69240>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by WhymustIhaveaname** [comment]
"一天内回复"：好 flag。。。抱歉最近在旅行，没能及时处理。

清华的认证系统需要提交一个 ac_id，这东西与在哪个楼有关，大部分时候是 1，不对有时候会导致连不上。我曾经在老水利馆、建筑系报告厅见过这个错误，但之后可能是我不去那里活动了就没见过了。

如果一定要解决，可以通过网页登陆，通过浏览器开发者功能network找到 ac_id，之后手动修改代码，也可以打电话给 its，有时候他们知道正确的 ac_id 是什么。

**Comment by azishabibi** [comment]
网页登录https://auth6.tsinghua.edu.cn/ ，输入帐号和密码后显示ip地址错误，请重新拿地址

**Comment by WhymustIhaveaname** [comment]
网页都不行脚本肯定不行的。这种情况直接打电话问 its 62784859
